import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from './pages/_app'
import { PopStateProvider, StateProvider, FocusProvider } from './toggleContext'
import { ThemeProvider } from '@/components/theme-provider'
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <StateProvider>
            <PopStateProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <FocusProvider>
                <ToastContainer autoClose={3000} />
                  {children}
                </FocusProvider>
              </ThemeProvider>
            </PopStateProvider>
          
          </StateProvider>

        </Provider>
        </body>
    </html>
  )
}
